export type CityProfile = {
  id: string;
  name: string;
  focus: string;
  description: string;
  localities: { id: string; name: string }[];
};

export const CITIES: Record<string, CityProfile> = {
  mumbai: {
    id: "mumbai",
    name: "Mumbai",
    focus: "General Beauty Marketplace",
    description: "The ultimate hub for all things beauty. Find top-rated salons, trending stylists, and everyday grooming.",
    localities: [
      { id: "bandra-west", name: "Bandra West" },
      { id: "andheri-west", name: "Andheri West" },
      { id: "juhu", name: "Juhu" },
      { id: "colaba", name: "Colaba" },
      { id: "powai", name: "Powai" },
      { id: "malad", name: "Malad" },
      { id: "goregaon", name: "Goregaon" },
      { id: "santacruz", name: "Santacruz" },
      { id: "khar", name: "Khar" },
      { id: "worli", name: "Worli" },
      { id: "lower-parel", name: "Lower Parel" },
      { id: "dadar", name: "Dadar" },
      { id: "chembur", name: "Chembur" },
      { id: "borivali", name: "Borivali" },
      { id: "kandivali", name: "Kandivali" },
    ],
  },
  bangalore: {
    id: "bangalore",
    name: "Bangalore",
    focus: "Luxury & Premium Experiences",
    description: "Exclusive VIP services and luxury salons designed for the ultimate premium grooming experience.",
    localities: [
      { id: "indiranagar", name: "Indiranagar" },
      { id: "koramangala", name: "Koramangala" },
      { id: "whitefield", name: "Whitefield" },
      { id: "lavelle-road", name: "Lavelle Road" },
      { id: "jayanagar", name: "Jayanagar" },
      { id: "jp-nagar", name: "JP Nagar" },
      { id: "hsr-layout", name: "HSR Layout" },
      { id: "sadashivanagar", name: "Sadashivanagar" },
      { id: "malleshwaram", name: "Malleshwaram" },
      { id: "richmond-town", name: "Richmond Town" },
      { id: "frazer-town", name: "Frazer Town" },
      { id: "marathahalli", name: "Marathahalli" },
      { id: "bellandur", name: "Bellandur" },
      { id: "electronic-city", name: "Electronic City" },
      { id: "yelahanka", name: "Yelahanka" },
    ],
  },
  delhi: {
    id: "delhi",
    name: "Delhi",
    focus: "Bridal Specialists & Wedding Planners",
    description: "The capital's finest bridal studios, wedding makeup artists, and pre-wedding specialists.",
    localities: [
      { id: "south-extension", name: "South Extension" },
      { id: "greater-kailash", name: "Greater Kailash" },
      { id: "vasant-kunj", name: "Vasant Kunj" },
      { id: "rajouri-garden", name: "Rajouri Garden" },
      { id: "defence-colony", name: "Defence Colony" },
      { id: "lajpat-nagar", name: "Lajpat Nagar" },
      { id: "hauz-khas", name: "Hauz Khas" },
      { id: "punjabi-bagh", name: "Punjabi Bagh" },
      { id: "pitampura", name: "Pitampura" },
      { id: "roहिणी", name: "Rohini" },
      { id: "dwarka", name: "Dwarka" },
      { id: "chanakyapuri", name: "Chanakyapuri" },
      { id: "karol-bagh", name: "Karol Bagh" },
      { id: "model-town", name: "Model Town" },
      { id: "saket", name: "Saket" },
    ],
  },
  pune: {
    id: "pune",
    name: "Pune",
    focus: "Home Salon & Travel Services",
    description: "Premium salon services delivered directly to your doorstep. Ultimate convenience.",
    localities: [
      { id: "koregaon-park", name: "Koregaon Park" },
      { id: "kalyani-nagar", name: "Kalyani Nagar" },
      { id: "viman-nagar", name: "Viman Nagar" },
      { id: "kothrud", name: "Kothrud" },
      { id: "baner", name: "Baner" },
      { id: "aundh", name: "Aundh" },
      { id: "wakad", name: "Wakad" },
      { id: "hinjewadi", name: "Hinjewadi" },
      { id: "kharadi", name: "Kharadi" },
      { id: "magarpatta", name: "Magarpatta" },
      { id: "hadapsar", name: "Hadapsar" },
      { id: "camp", name: "Camp" },
      { id: "shivajinagar", name: "Shivajinagar" },
      { id: "pimple-saudagar", name: "Pimple Saudagar" },
      { id: "bavdhan", name: "Bavdhan" },
    ],
  },
  hyderabad: {
    id: "hyderabad",
    name: "Hyderabad",
    focus: "Men's Grooming Marketplace",
    description: "Elite barbershops, beard styling, and premium men's grooming centers.",
    localities: [
      { id: "jubilee-hills", name: "Jubilee Hills" },
      { id: "banjara-hills", name: "Banjara Hills" },
      { id: "hitec-city", name: "HITEC City" },
      { id: "gachibowli", name: "Gachibowli" },
      { id: "kondapur", name: "Kondapur" },
      { id: "madhapur", name: "Madhapur" },
      { id: "kukatapally", name: "Kukatpally" },
      { id: "secunderabad", name: "Secunderabad" },
      { id: "begumpet", name: "Begumpet" },
      { id: "somajiguda", name: "Somajiguda" },
      { id: "ameerpet", name: "Ameerpet" },
      { id: "tolichowki", name: "Tolichowki" },
      { id: "manikonda", name: "Manikonda" },
      { id: "miyapur", name: "Miyapur" },
      { id: "uppal", name: "Uppal" },
    ],
  },
};

export const getCityById = (id: string): CityProfile | undefined => CITIES[id.toLowerCase()];
